#ifndef HLL_C4D_SYMBOLS_H__
#define HLL_C4D_SYMBOLS_H__

enum
{
	_DUMMY_ELEMENT_ = 10000,

	DLG_HLL,
	BTN_LISTEN,
	TXT_HOSTNAME,
	TXT_PORT,
	STR_START_LISTEN,
	STR_STOP_LISTEN,
	BTN_SETCAMERA,
	TXT_CAMERANAME,
	BTN_MAPPING,
	LV_CLIENTS,
	TXT_STATUS,
	STR_NO_REPORT,
	STR_NO_CAMERA,
	BTN_COPY_URI,

	STR_CLIENT_CONNECT,
	STR_CLIENT,
	STR_HELLO_CLIENT,
	STR_STARTING_SERVER,
	STR_HOST,
	STR_PORT,
	STR_UNEXPECTED_ERROR,
	STR_DISCONNECT,
	STR_CLIENT_DISCONNECT,
	STR_SERVER_RENAME,
	STR_SERVER_DISCONNECT,
	STR_SERVER_DISCONNECT_SERVERSIDE,
	STR_TARGET_CSGO,
	STR_TARGET_CINEMA4D,
	STR_STARTING_LISTEN,
	STR_LISTEN_FAILED,
	STR_LISTEN,
	STR_RESTART,
	STR_LISTEN_SERVER_CLOSED,
	STR_NOT_A_CAMERA,
	STR_CAM_NO_SELECT,
	STR_ACTIVE_CLIENT,
	STR_BAD_DATASTART,
	STR_BAD_DATASTART_C,
	STR_BAD_DATASTOP,
	STR_LIVE_CLIENT,
	STR_INACTIVE_CLIENT
};

#endif // !HLL_C4D_SYMBOLS_H__
