#ifndef HLL_C4D_SYMBOLS_H__
#define HLL_C4D_SYMBOLS_H__

enum
{
	_DUMMY_ELEMENT_ = 10000,

	DLG_HLL,
	BTN_LISTEN,
	TXT_HOSTNAME,
	TXT_PORT,
	STR_START_LISTEN,
	STR_STOP_LISTEN,
	CBX_COORDINATE_SYSTEM,
	CBO_Y_UP,
	CBO_NZ_UP,
	BTN_SETCAMERA,
	TXT_CAMERANAME,
	BTN_MAPPING,
	LV_CLIENTS,
	TXT_STATUS,
	STR_NO_REPORT,
	STR_NO_CAMERA,

	STR_CLIENT_CONNECT,
	STR_CLIENT,
	STR_HELLO_CLIENT,
	STR_STARTING_SERVER,
	STR_HOST,
	STR_PORT,
	STR_UNEXPECTED_ERROR,
	STR_DISCONNECT,
	STR_CLIENT_DISCONNECT,
	STR_SERVER_RENAME,
	STR_SERVER_DISCONNECT,
	STR_SERVER_DISCONNECT_SERVERSIDE
};

#endif // !HLL_C4D_SYMBOLS_H__
