// C4D-DialogResource

DIALOG DLG_HLL
{
	NAME DLG_HLL_TITLE;
	SCALE_H; SCALE_V;
  
	GROUP
	{
		BORDERSIZE 12,12,12,12;
		COLUMNS 1;
		SCALE_H; SCALE_V;
		
		USERAREA IMG_BANNER { SCALE_H; CENTER_H; }
		
		GROUP
		{
			COLUMNS 5;
			SCALE_H;
			
			BUTTON BTN_LISTEN { SIZE 150, 0; }
			
			STATICTEXT { NAME STR_HOSTNAME; }
			EDITTEXT ETXT_HOSTNAME { SCALE_H; }
			
			STATICTEXT { NAME STR_PORT; }
			EDITNUMBERARROWS ETXT_PORT { SIZE 80, 0; }
		}
		
		SEPARATOR { SCALE_H; }

		GROUP
		{
			COLUMNS 3;
			STATICTEXT { NAME STR_POLLRATE; }
			EDITNUMBERARROWS ETXT_POLLRATE { SIZE 80, 0; }
		}
		
		GROUP
		{
			COLUMNS 6;	
			BORDERSIZE 10,0,0,0;
			SIZE -300, 0;

			STATICTEXT { NAME STR_FTIME; }
			STATICTEXT TXT_FTIME { CENTER_H; SCALE_H; }
			
			STATICTEXT { NAME STR_AVGTIME; }
			STATICTEXT TXT_AVGTIME { CENTER_H; SCALE_H; }
			
			STATICTEXT { NAME STR_MAXTIME; }
			STATICTEXT TXT_MAXTIME { CENTER_H; SCALE_H; }
		}

		SEPARATOR { SCALE_H; }

		CHECKBOX CHK_USE_GLOBAL_POSROT { NAME STR_USE_GLOBAL_POSROT; }

		GROUP
		{
			COLUMNS 4;
			STATICTEXT { NAME STR_ORIENTATION; }
			EDITNUMBERARROWS VEC_ORIENTATION_X { }
			EDITNUMBERARROWS VEC_ORIENTATION_Y { }
			EDITNUMBERARROWS VEC_ORIENTATION_Z { }
		}

		SEPARATOR { SCALE_H; }
	
		GROUP
		{
			COLUMNS 2;
			SCALE_H;
			
			GROUP
			{
				BUTTON BTN_SETCAMERA { NAME STR_SETCAMERA; SCALE_H; }
			}
			STATICTEXT TXT_CAMERANAME { SCALE_H; }
		}

		
		GROUP
		{
			COLUMNS 2;
			STATICTEXT { NAME STR_MAPPING; }
			GROUP
			{
				COLUMNS 3;

				STATICTEXT { NAME STR_CINEMA4D; }
				BUTTON BTN_MAPPING { SIZE 30, 0; }
				STATICTEXT { NAME STR_GAME; }			
			}
		}
		
		SEPARATOR { SCALE_H; }
		
		BUTTON BTN_COPY_URI { NAME STR_COPY_URI; }
		GROUP
		{
			SCALE_H; SCALE_V;
			LISTVIEW LV_CLIENTS { SCALE_H; SCALE_V; }
		}
		
		SEPARATOR { SCALE_H; }

		GROUP
		{
			BORDERSTYLE BORDER_ACTIVE_4;
			SCALE_H;
			BORDERSIZE 2,2,2,2;
			ALIGN_BOTTOM;
			
			STATICTEXT TXT_STATUS { SCALE_H; }
		}
	}
}
